#
# Configuration variables
#

# Use the Slate theme for the base look-and-feel.
theme: jekyll-theme-slate

# Title of the GitHub pages user site.
title: Shiny Object Affliction

description: My investigations and musings on cool tech

# Set the timezone.
timezone: America/Denver

# The user site doesn't use the downloads feature of the slate theme.
show_downloads: false

gems:
   - jekyll-avatar    # Gem to get the GitHub avatar
